# Generated by Django 2.2.5 on 2019-11-12 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0038_auto_20191112_0258'),
        ('calendarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='aca',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='e_aca', to='acagiaApp.Academy'),
            preserve_default=False,
        ),
    ]
