# Generated by Django 2.2.5 on 2019-10-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0002_auto_20191023_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
