# Generated by Django 2.2.5 on 2019-10-25 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0004_auto_20191023_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='addr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aca_addr', to='acagiaApp.Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='acagiaApp.Course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='stu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attend_stu', to='acagiaApp.Student'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_stu', to='acagiaApp.Student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst', to='acagiaApp.Instructor'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='mem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inst_detail', to='acagiaApp.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='aca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aca', to='acagiaApp.Academy'),
        ),
        migrations.AlterField(
            model_name='member',
            name='addr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mem_addr', to='acagiaApp.Address'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_stu', to='acagiaApp.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stu_detail', to='acagiaApp.Member'),
        ),
    ]
