# Generated by Django 2.2.5 on 2019-10-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0005_auto_20191025_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='stu',
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mem_attended', to='acagiaApp.Member'),
        ),
        migrations.AlterField(
            model_name='academy',
            name='aca_type',
            field=models.CharField(choices=[('General', 'General'), ('MMA', 'MMA')], default='General', max_length=10),
        ),
    ]
