# Generated by Django 2.2.5 on 2019-10-26 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0006_auto_20191026_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='aca',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='atten_aca', to='acagiaApp.Academy'),
            preserve_default=False,
        ),
    ]
