# Generated by Django 2.2.5 on 2019-10-26 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0007_attendance_aca'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time_attended',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_attended',
            field=models.DateField(auto_now_add=True),
        ),
    ]
