# Generated by Django 2.2.5 on 2019-10-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0009_auto_20191026_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(blank=True, height_field='300', null=True, upload_to='mem_photos/', width_field='200'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='Active', max_length=7),
        ),
    ]
