# Generated by Django 2.2.5 on 2019-10-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0013_auto_20191029_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mem_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor'), ('Other', 'Other')], default='Student', max_length=10),
        ),
    ]
