# Generated by Django 2.2.5 on 2019-10-31 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0015_auto_20191030_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=30)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('reward', models.CharField(blank=True, max_length=20, null=True)),
                ('aca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se_aca', to='acagiaApp.Academy')),
                ('event', models.ForeignKey(on_delete=models.SET('Deleted'), related_name='se_event', to='acagiaApp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_at_this_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentevent',
            name='aca',
        ),
        migrations.RemoveField(
            model_name='studentevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='studentevent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentrank',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='studentrank',
            name='student',
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='Active', max_length=7),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_days',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_inst', to='acagiaApp.Member'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentEvent',
        ),
        migrations.DeleteModel(
            name='StudentRank',
        ),
        migrations.AddField(
            model_name='memberrank',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_mem', to='acagiaApp.Member'),
        ),
        migrations.AddField(
            model_name='memberrank',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sr_rank', to='acagiaApp.Rank'),
        ),
        migrations.AddField(
            model_name='memberevent',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se_mem', to='acagiaApp.Member'),
        ),
    ]
