# Generated by Django 2.2.5 on 2019-11-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0016_auto_20191031_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='member',
            name='addr',
        ),
        migrations.AddField(
            model_name='academy',
            name='location',
            field=models.CharField(default='Fremont', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N/A', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=35),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
