# Generated by Django 2.2.5 on 2019-11-02 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0017_auto_20191102_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='att_course', to='acagiaApp.Course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_mem', to='acagiaApp.Member'),
        ),
        migrations.AlterField(
            model_name='memberevent',
            name='aca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_aca', to='acagiaApp.Academy'),
        ),
        migrations.AlterField(
            model_name='memberevent',
            name='event',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), related_name='me_event', to='acagiaApp.Event'),
        ),
        migrations.AlterField(
            model_name='memberevent',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_mem', to='acagiaApp.Member'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.CharField(choices=[('Novice', 'Novice'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Master', 'Master')], default='None', max_length=10),
        ),
    ]
