# Generated by Django 2.2.5 on 2019-11-03 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0020_auto_20191102_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_attended',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_attended',
            field=models.TimeField(default='21:32:18', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(blank=True, default='mem_photos/no-img.png', null=True, upload_to='mem_photos/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Hold', 'Hold')], default='Active', max_length=8),
        ),
    ]
