# Generated by Django 2.2.5 on 2019-11-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0022_auto_20191106_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_attended',
            field=models.DateField(default='2019-11-06'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_attended',
            field=models.TimeField(default='01:33:09'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateField(default='2019-11-06', null=True),
        ),
    ]
