# Generated by Django 2.2.5 on 2019-11-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0023_auto_20191106_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_attended',
            field=models.TimeField(default='01:47:24'),
        ),
    ]
