# Generated by Django 2.2.5 on 2019-11-07 04:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0024_auto_20191106_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='e_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='e_name',
        ),
        migrations.RenameField(
            model_name='memberrank',
            old_name='days_at_this_rank',
            new_name='days_attended',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='e_end_time',
            field=models.TimeField(default=datetime.datetime(2019, 11, 7, 4, 57, 36, 837545, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='e_location',
            field=models.CharField(default=datetime.datetime(2019, 11, 7, 4, 57, 46, 840397, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='e_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='e_start_time',
            field=models.TimeField(default=datetime.datetime(2019, 11, 7, 4, 58, 57, 423144, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberrank',
            name='total_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rank',
            name='aca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rank_aca', to='acagiaApp.Academy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rank',
            name='days_required',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rank',
            name='rank_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_attended',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_attended',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateField(default=datetime.date(2019, 11, 7)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberrank',
            name='rank',
            field=models.CharField(default='White', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank_type',
            field=models.CharField(choices=[('BJJ', 'Jiu-jitsu'), ('General', 'General'), ('TKD', 'Taekwondo')], max_length=10),
        ),
    ]
