# Generated by Django 2.2.5 on 2019-11-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0025_auto_20191107_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank_type',
            field=models.CharField(choices=[('Jiu-jitsu', 'Jiu-jitsu'), ('General', 'General'), ('Taekwondo', 'Taekwondo')], max_length=10),
        ),
    ]
