# Generated by Django 2.2.5 on 2019-11-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0026_auto_20191108_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrank',
            name='days_attended',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='memberrank',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mr_mem', to='acagiaApp.Member'),
        ),
        migrations.AlterField(
            model_name='memberrank',
            name='rank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mr_rank', to='acagiaApp.Rank'),
        ),
        migrations.AlterField(
            model_name='memberrank',
            name='total_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank_type',
            field=models.CharField(choices=[('Custom', 'Custom'), ('Jiu-jitsu', 'Jiu-jitsu'), ('General', 'General'), ('Taekwondo', 'Taekwondo')], max_length=10),
        ),
    ]
