# Generated by Django 2.2.5 on 2019-11-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0027_auto_20191108_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='rank_sys',
            field=models.CharField(default='My jiu-jitsu', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academy',
            name='aca_type',
            field=models.CharField(choices=[('General', 'General'), ('Jiu-jitsu', 'Jiu-jitsu'), ('MMA', 'MMA'), ('Taekwondo', 'Taekwondo')], default='General', max_length=10),
        ),
        migrations.AlterField(
            model_name='memberrank',
            name='days_attended',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='memberrank',
            name='total_days',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
