# Generated by Django 2.2.5 on 2019-11-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0028_auto_20191108_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='rank_type',
        ),
    ]
