# Generated by Django 2.2.5 on 2019-11-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0029_remove_rank_rank_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrank',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mr_mem', to='acagiaApp.Member'),
        ),
    ]
