# Generated by Django 2.2.5 on 2019-11-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0030_auto_20191108_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrank',
            name='rank',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mr_rank', to='acagiaApp.Rank'),
        ),
    ]
