# Generated by Django 2.2.5 on 2019-11-08 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0031_auto_20191108_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrank',
            name='aca',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='mr_aca', to='acagiaApp.Academy'),
            preserve_default=False,
        ),
    ]
