# Generated by Django 2.2.5 on 2019-11-09 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0033_auto_20191109_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrank',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mr_rank', to='acagiaApp.Rank'),
        ),
    ]
