# Generated by Django 2.2.5 on 2019-11-13 00:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0034_auto_20191109_0529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='e_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='e_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='e_end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='e_location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='e_note',
        ),
        migrations.RemoveField(
            model_name='event',
            name='e_start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='aca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='e_aca', to='acagiaApp.Academy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
