# Generated by Django 2.2.5 on 2019-11-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0035_auto_20191113_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='rank_sys',
        ),
    ]
