# Generated by Django 2.2.5 on 2019-12-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0038_auto_20191215_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberevent',
            name='weight',
        ),
        migrations.AlterField(
            model_name='memberevent',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_event', to='acagiaApp.Event'),
        ),
    ]
