# Generated by Django 2.2.5 on 2019-12-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0039_auto_20191215_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberevent',
            name='aca',
        ),
    ]
