# Generated by Django 2.2.5 on 2020-01-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0040_remove_memberevent_aca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.CharField(max_length=255),
        ),
    ]
