# Generated by Django 2.2.5 on 2020-01-18 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0040_remove_memberevent_aca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpayment',
            name='last_payment',
        ),
        migrations.RemoveField(
            model_name='memberpayment',
            name='payday',
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='late_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='month_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='nth_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='PayTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('every_n_month', models.IntegerField(default=1)),
                ('install_factor', models.IntegerField(null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('aca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_term_aca', to='acagiaApp.Academy')),
            ],
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='pay_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acagiaApp.PayTerm'),
        ),
    ]
