# Generated by Django 2.2.5 on 2020-01-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0042_auto_20200118_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentterm',
            old_name='every_n_month',
            new_name='n_month',
        ),
    ]
