# Generated by Django 2.2.5 on 2020-01-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0043_auto_20200119_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentterm',
            old_name='n_month',
            new_name='recurrence',
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='install_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
