# Generated by Django 2.2.5 on 2020-01-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0044_auto_20200119_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentterm',
            old_name='recurrence',
            new_name='n_month',
        ),
    ]
