# Generated by Django 2.2.5 on 2020-01-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0045_auto_20200120_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentterm',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='install_factor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
