# Generated by Django 2.2.5 on 2020-01-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0047_auto_20200122_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentterm',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
