# Generated by Django 2.2.5 on 2020-01-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0049_auto_20200122_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpayment',
            name='aca',
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='month_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=6),
        ),
    ]
