# Generated by Django 2.2.5 on 2020-02-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0050_auto_20200126_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberpayment',
            old_name='status',
            new_name='pay_status',
        ),
    ]
