# Generated by Django 2.2.5 on 2020-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acagiaApp', '0052_memberrank_days_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(blank=True, default='mem_photos/no-img.png', null=True, upload_to='mem_photos/%Y/%m/%d/'),
        ),
    ]
